# Generated by Django 5.1.4 on 2024-12-27 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0003_alter_customuser_password_alter_customuser_studentid_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='custom_user',
        ),
    ]
