# Generated by Django 5.1.4 on 2025-01-07 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0005_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like',
        ),
    ]
