# Generated by Django 5.1.4 on 2025-01-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0007_alter_profile_fav_alter_profile_hobby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
